server:
  port: 9000
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      
# http://www.h2database.com/html/features.html#connection_modes
#  datasource:
#    url: jdbc:h2:mem:tempdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE